In [ ]:
##Sparse Matrices - which are regular matrices that do only store elements that exhibit a value different from zero. 
"""
seven sparse matrix types in scipy.sparse:
csc_matrix: Compressed Sparse Column format
csr_matrix: Compressed Sparse Row format
bsr_matrix: Block Sparse Row format
lil_matrix: List of Lists format
dok_matrix: Dictionary of Keys format
coo_matrix: COOrdinate format (aka IJV, triplet format)
dia_matrix: DIAgonal format
"""
import numpy as np
import scipy.sparse as sps
import matplotlib.pyplot as plt
from scipy.sparse import csr_matrix

# To do a vector product between a sparse matrix and a vector simply use the matrix dot method, as described in its docstring:


In [4]:
#Construct a matrix in COO format:
from scipy import sparse
from numpy import array
I = array([0,3,1,0])
J = array([0,3,1,2])
V = array([4,5,7,9])
A = sparse.coo_matrix((V,(I,J)),shape=(4,4))
#print(A)

"""
Notice that the indices do not need to be sorted.

Duplicate (i,j) entries are summed when converting to CSR or CSC."""
I = array([0,0,1,3,1,0,0])
J = array([0,2,1,3,1,0,0])
V = array([1,1,1,1,1,1,1])
B = sparse.coo_matrix((V,(I,J)),shape=(4,4)).tocsr()
print(I)
print(J)
print(V)
print(B)

[0 0 1 3 1 0 0]
[0 2 1 3 1 0 0]
[1 1 1 1 1 1 1]
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
  (3, 3)	1


In [12]:
## Diagonal Matrix
import numpy as np
data = np.array([[1, 2, 3, 4]]).repeat(3, axis=0)
data

offsets = np.array([0, -1, 2])
mtx = sparse.dia_matrix((data, offsets), shape=(4, 4))
mtx  
print(mtx)
mtx.todense()


  (0, 0)	1
  (1, 1)	2
  (2, 2)	3
  (3, 3)	4
  (1, 0)	1
  (2, 1)	2
  (3, 2)	3
  (0, 2)	3
  (1, 3)	4


matrix([[1, 0, 3, 0],
        [1, 2, 0, 4],
        [0, 2, 3, 0],
        [0, 0, 3, 4]])

In [15]:
data = np.arange(12).reshape((3, 4)) + 1
data



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
mtx = sparse.dia_matrix((data, offsets), shape=(4, 4))
mtx.data 
mtx.offsets
print(mtx)

  (0, 0)	1
  (1, 1)	2
  (2, 2)	3
  (3, 3)	4
  (1, 0)	5
  (2, 1)	6
  (3, 2)	7
  (0, 2)	11
  (1, 3)	12


In [21]:
vec = np.ones((4, ))
vec

mtx * vec

mtx.toarray() * vec

array([[  1.,   0.,  11.,   0.],
       [  5.,   2.,   0.,  12.],
       [  0.,   6.,   3.,   0.],
       [  0.,   0.,   7.,   4.]])

In [27]:
## Lists of Lists format
"""
each row is a Python list (sorted) of column indices of non-zero elements
efficient for constructing sparse matrices incrementally
flexible slicing, changing sparsity structure is efficient
slow arithmetics, slow column slicing due to being row-based
use:
when sparsity pattern is not known apriori or changes
example: reading a sparse matrix from a text file
"""
mtx = sparse.lil_matrix((4, 5))

#random data
from numpy.random import rand
data = np.round(rand(2, 3))
data

#assign the data using indexing
mtx[:2, [1, 2, 3]] = data
mtx  
print(mtx)

mtx.todense()
mtx.toarray()



  (1, 2)	1.0
  (1, 3)	1.0


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [31]:
#slicing and indexing
mtx = sparse.lil_matrix([[0, 1, 2, 0], [3, 0, 1, 0], [1, 0, 0, 1]])
mtx.todense()    

print(mtx)




  (0, 1)	1
  (0, 2)	2
  (1, 0)	3
  (1, 2)	1
  (2, 0)	1
  (2, 3)	1


<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in LInked List format>

In [36]:
mtx[:2, :]
mtx[:2, :].todense()
mtx[1:2, [0,2]].todense()
mtx.todense()

matrix([[0, 1, 2, 0],
        [3, 0, 1, 0],
        [1, 0, 0, 1]], dtype=int64)

In [43]:
##Dictinoary of Key Format
"""
subclass of Python dict
keys are (row, column) index tuples (no duplicate entries allowed)
values are corresponding non-zero values
efficient for constructing sparse matrices incrementally
flexible slicing, changing sparsity structure is efficient
can be efficiently converted to a coo_matrix once constructed
slow arithmetics (for loops with dict.iteritems())
use:
when sparsity pattern is not known apriori or changes
"""

#create a DOK matrix element by element:

mtx = sparse.dok_matrix((5, 5), dtype=np.float64)
mtx 

for ir in range(5):
    for ic in range(5):
        mtx[ir, ic] = 1.0 * (ir != ic)
mtx
print(mtx)
mtx.todense()

  (1, 2)	1.0
  (3, 2)	1.0
  (1, 3)	1.0
  (3, 0)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (1, 4)	1.0
  (4, 2)	1.0
  (1, 0)	1.0
  (0, 3)	1.0
  (4, 0)	1.0
  (0, 1)	1.0
  (3, 4)	1.0
  (3, 1)	1.0
  (2, 4)	1.0
  (2, 0)	1.0
  (4, 3)	1.0
  (0, 4)	1.0
  (4, 1)	1.0
  (0, 2)	1.0


matrix([[ 0.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  1.,  1.,  1.],
        [ 1.,  1.,  0.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  1.],
        [ 1.,  1.,  1.,  1.,  0.]])

In [48]:
## Coordinate Format
"""
also known as the ‘ijv’ or ‘triplet’ format
three NumPy arrays: row, col, data
data[i] is value at (row[i], col[i]) position
permits duplicate entries
fast format for constructing sparse matrices
very fast conversion to and from CSR/CSC formats
fast matrix * vector (sparsetools)
fast and easy item-wise operations
manipulate data array directly (fast NumPy machinery)
no slicing, no arithmetics (directly)
use:
facilitates fast conversion among sparse formats
when converting to other format (usually CSR or CSC), duplicate entries are summed together
facilitates efficient construction of finite element matrices
"""
#Empty matrix
mtx = sparse.coo_matrix((3, 4), dtype=np.int8)
mtx.todense()

# input data using (data,i,j)tuple
row = np.array([0, 3, 1, 0])
col = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])
mtx = sparse.coo_matrix((data, (row, col)), shape=(4, 4))
mtx
print(mtx)
mtx.todense()

## Duplicate entries are summed up together
row = np.array([0, 0, 1, 3, 1, 0, 0])
col = np.array([0, 2, 1, 3, 1, 0, 0])
data = np.array([1, 1, 1, 1, 1, 1, 1])
mtx = sparse.coo_matrix((data, (row, col)), shape=(4, 4))
mtx.todense()

  (0, 0)	4
  (3, 3)	5
  (1, 1)	7
  (0, 2)	9


matrix([[3, 0, 1, 0],
        [0, 2, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1]])

In [55]:
## Compressed Sparse Row Format
"""
row oriented
three NumPy arrays: indices, indptr, data
indices is array of column indices
data is array of corresponding nonzero values
indptr points to row starts in indices and data
length is n_row + 1, last item = number of values = length of both indices and data
nonzero values of the i-th row are data[indptr[i]:indptr[i+1]] with column indices indices[indptr[i]:indptr[i+1]]
item (i, j) can be accessed as data[indptr[i]+k], where k is position of j in indices[indptr[i]:indptr[i+1]]
fast matrix vector products and other arithmetics (sparsetools)
efficient row slicing, row-oriented operations
slow column slicing, expensive changes to the sparsity structure
use:
actual computations (most linear solvers support this format)
"""

#create CSR matrix
mtx = sparse.csr_matrix((3, 4), dtype=np.int8)
mtx.todense()

#create data
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = sparse.csr_matrix((data, (row, col)), shape=(3, 3))
mtx 
mtx.todense()
mtx.data  
mtx.indices
mtx.indptr

#create using (data, indices, indptr) tuple:
data = np.array([1, 2, 3, 4, 5, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
indptr = np.array([0, 2, 3, 6])
mtx = sparse.csr_matrix((data, indices, indptr), shape=(3, 3))
mtx.todense()

matrix([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]])

In [59]:
## Compressed Sparse Column Format (CSC)
"""
column oriented
three NumPy arrays: indices, indptr, data
indices is array of row indices
data is array of corresponding nonzero values
indptr points to column starts in indices and data
length is n_col + 1, last item = number of values = length of both indices and data
nonzero values of the i-th column are data[indptr[i]:indptr[i+1]] with row indices indices[indptr[i]:indptr[i+1]]
item (i, j) can be accessed as data[indptr[j]+k], where k is position of i in indices[indptr[j]:indptr[j+1]]

fast matrix vector products and other arithmetics (sparsetools)

efficient column slicing, column-oriented operations
slow row slicing, expensive changes to the sparsity structure
use:
actual computations (most linear solvers support this format)

"""

mtx = sparse.csc_matrix((3, 4), dtype=np.int8)
mtx.todense()

# create using (data, ij) tuple:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = sparse.csc_matrix((data, (row, col)), shape=(3, 3))
mtx         


mtx.todense() 
mtx.data   

mtx.indices

mtx.indptr

#create using (data, indices, indptr) tuple:
data = np.array([1, 4, 5, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
indptr = np.array([0, 2, 3, 6])
mtx = sparse.csc_matrix((data, indices, indptr), shape=(3, 3))
mtx.todense()


matrix([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]])

In [68]:
## Block Compressed Row Format 
"""
basically a CSR with dense sub-matrices of fixed shape instead of scalar items
block size (R, C) must evenly divide the shape of the matrix (M, N)
three NumPy arrays: indices, indptr, data
indices is array of column indices for each block
data is array of corresponding nonzero values of shape (nnz, R, C)

fast matrix vector products and other arithmetics (sparsetools)

many arithmetic operations considerably more efficient than CSR for sparse matrices with dense sub-matrices
use:
like CSR
vector-valued finite element discretizations

"""

mtx = sparse.bsr_matrix((3, 4), dtype=np.int8)
mtx  


mtx.todense()

# create empty BSR matrix with (3, 2) block size:
mtx = sparse.bsr_matrix((3, 4), blocksize=(3, 2), dtype=np.int8)
mtx  


mtx.todense()

# create using (data, ij) tuple with (1, 1) block size (like CSR...):
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = sparse.bsr_matrix((data, (row, col)), shape=(3, 3))
mtx 

mtx.todense()  

mtx.data
mtx.indices

mtx.indptr

#create using (data, indices, indptr) tuple with (2, 2) block size:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6]).repeat(4).reshape(6, 2, 2)
mtx = sparse.bsr_matrix((data, indices, indptr), shape=(6, 6))
mtx.todense()
data

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4]],

       [[5, 5],
        [5, 5]],

       [[6, 6],
        [6, 6]]])